Restaurant/Restaurant/Models/DishCompositionViewModel.cs
using Business.Models;

namespace Restaurant.Models
{
    public class DishCompositionViewModel
    {
        public decimal Amount { get; set; }
        public string SelectDishId { get; set; }
        public string SelectIngredientId { get; set; }


    }
}

Restaurant/Restaurant/Controllers/DishCompositionController.cs
using Business.Services;
using Business.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Business.Models;
using Microsoft.AspNetCore.Authorization;
using Restaurant.Models;
using Data.Entities;
using System.Linq;

namespace Restaurant.Controllers
{
    public class DishCompositionController : Controller
    {

        private readonly ILogger<DishController> _logger;
        private readonly IDishCompositionService _dishCompositionService;
        private readonly IIngredientService _ingredientService;
        private readonly IDishService _dishService;

        public DishCompositionController(ILogger<DishController> logger, IDishCompositionService dishCompositionService, IIngredientService ingredientService,
            IDishService dishService)
        {
            _logger = logger;
            _dishCompositionService = dishCompositionService;
            _ingredientService = ingredientService;
            _dishService = dishService;
        }

        [Authorize(Policy = "RequireAdmin")]
        public async Task<IActionResult> DetailsAsync(int id)
        {
            var dishes = await _dishCompositionService.GetAllAsync();



            return View(dishes);
        }

        [HttpPost]
        [Authorize(Policy = "RequireAdmin")]
        public async Task<IActionResult> CreateAsync(DishCompositionViewModel model)
        {
            if (ModelState.IsValid)
            {     
                var dishes = await _dishService.GetAllAsync();
                var dish = dishes.Where(i => i.Name == model.SelectDishId).FirstOrDefault();

                var ingredients = await _ingredientService.GetAllAsync();
                var ingredient = ingredients.Where(i => i.Name == model.SelectIngredientId).FirstOrDefault();


                DishCompositionModel dcm = new()
                {
                    Amount = model.Amount,
                    DishId = dish.Id,
                    IngredientId = ingredient.Id
                };

                await _dishCompositionService.AddAsync(dcm);
                return RedirectToAction("Details");
            }
            return RedirectToAction("Create");
        }

        [Authorize(Policy = "RequireAdmin")]
        public ActionResult Create()
        {
            return View();
        }



        [HttpGet]
        [Authorize(Policy = "RequireAdmin")]
        public async Task<ActionResult> EditAsync(int id)
        {
            var dishcomposition = await _dishCompositionService.GetByIdAsync(id);

            DishCompositionEditViewModel dcmodel = new()
            {
                Id = dishcomposition.Id,
                Amount = dishcomposition.Amount,
                IngredientId = dishcomposition.Id,
                DishId = dishcomposition.DishId
            };

            return View(dcmodel);
        }

        [HttpPost]
        [Authorize(Policy = "RequireAdmin")]
        public async Task<ActionResult> EditAsync(DishCompositionEditViewModel model)
        {

            if (ModelState.IsValid)
            {
                DishCompositionModel dcmodel = new()
                {
                    Id = model.Id,
                    Amount = model.Amount,
                    IngredientId = model.Id,
                    DishId = model.DishId
                };

                await _dishCompositionService.UpdateAsync(dcmodel);
                return RedirectToAction("Details");
            }

            return RedirectToAction("Edit");
        }

        [Authorize(Policy = "RequireAdmin")]
        public async Task<IActionResult> DeleteAsync(int id)
        {
            await _dishCompositionService.DeleteAsync(id);
            return RedirectToAction("Details");
        }


    }
}

Restaurant/Restaurant/Views/DishComposition/Create.cshtml
@using System.Collections;
@using Data.Entities;
@using Business.Models;
@using Business.Interfaces;
@using System.Linq;

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers


@model DishCompositionViewModel


@inject IIngredientService ingredientService
@inject IDishService dishService

@{
    var ingr_names = (await ingredientService.GetAllAsync()).ToList().Select(o => o.Name);
    var dish_names = (await dishService.GetAllAsync()).ToList().Select(o => o.Name);
            ViewData["Title"] = "Create Dish Composition";
}


<div class="container shadow p-5">
    <div class="form-group d-flex justify-content-center">
        <h2>Add Dish Composition</h2>
    </div>



    <form method="post">
        <div asp-validation-summary="All"></div>        

        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th scope="col">Choose Dish:</th>
                    <th scope="col">Choose Ingredient:</th>
                    <th scope="col">Amount </th>
                </tr>
            </thead>

            <tbody>
            <tr>
                        <td width="33%">
                            <div class="form-row">                                                              
                                    @Html.DropDownList("SelectDishId", new SelectList(dish_names), new { @class="dropdown" })
                                
                            </div>
                        </td>
                    <td width="33%">
                        <div class="form-row">
                            @Html.DropDownList("SelectIngredientId", new SelectList(ingr_names), new { @class="dropdown" })

                        </div>
                    </td>
                        <td width="33%">
                            <div class="form-row">                                                                    
                                    <input type="text" class="form-control mb-3" asp-for="Amount" placeholder="Amount">
                                    <span asp-validation-for="Amount" class=" alert-danger"></span>                                           
                            </div>
                        </td>
                        
            <tr>
            </tbody>
        </table>


        <div class="form-group d-flex justify-content-center">            
            <button type="submit" class="btn btn-lg btn-primary p-2"><i class="bi bi-file-plus-fill"></i>Save</button>
            <div>&nbsp;</div>
            <div>&nbsp;</div>
            <div>&nbsp;</div>
            <a asp-controller="DishComposition" asp-action="Details" class="btn btn-lg btn-warning p-2">Back To List</a>
        </div>         
        
    </form>






</div>




<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.5.1.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/jquery.validate.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.10/jquery.validate.unobtrusive.min.js"></script>

Restaurant/Restaurant/Views/DishComposition/Delete.cshtml
@using System.Collections;
@using Business.Models
@using Data.Entities;

@model DishCompositionModel

<div class="container shadow p-5">
    <div class="row pb-2">
        <h2>Delete DishComposition</h2>
    </div>

    <form method="post">
        <input asp-for="Id" hidden />
        <div asp-validation-summary="All"></div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="Amount">Amount</label>
                <input type="text" class="form-control mb-3" asp-for="Amount" placeholder="Amount">
                <span asp-validation-for="Amount" class=" alert-danger"></span>
            </div>            
        </div>



        <button type="submit" class="btn btn-lg btn-danger p-2"><i class="bi bi-trash-fill"></i>Delete</button>        
        <a asp-controller="DishComposition" asp-action="Details" class="btn btn-lg btn-warning p-2">Back To List</a>
    </form>

} 

</div>

Restaurant/Restaurant/Views/DishComposition/Details.cshtml
@using System.Collections;
@using Data.Entities;
@using Business.Models;
@using Business.Interfaces;
@using System.Linq;



@model IEnumerable<DishCompositionModel>
    
@inject IIngredientService ingredientService
@inject IDishService dishService

@{
    var ingredients = (await ingredientService.GetAllAsync()).ToList().Select(ingr => new
    {
        Name = ingr.Name,
        Id = ingr.Id
    }); 
        
    var dishes = (await dishService.GetAllAsync()).ToList().Select(o => o.Name);

        ViewData["Title"] = "Dish Composition";



}

<link rel="stylesheet" href="~/css/ingredient.css">      
<h1 align="center">Dish Composition</h1>

<div class="container shadow p-5">
<div class="wrapper">
    <div id="formContent">
        <form asp-controller="DishComposition" asp-action="Create">
        <input type="submit" class="fadeIn" value="Add Dish Composition" />
</form>
</div>
</div>
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Dish Name</th>
                <th scope="col">Ingredient Name</th>
                <th scope="col">Amount</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model)
            {
                <tr>
                    <td width="3%">
                        @item.Id
                    </td>
                    <td width="20%">
                        @dishService.GetByIdAsync(item.DishId).Result.Name
                    </td>  
                    <td width="20%">
                        @ingredientService.GetByIdAsync(item.IngredientId).Result.Name
                    </td> 
                    <td width="20%">
                        @item.Amount
                    </td>   
                    <td width="15%">
                        @ingredientService.GetByIdAsync(item.IngredientId).Result.IngredientMeasurement
                    </td>  
                    <td>
                        <div role="group" class="w-60 btn-group">
                            <a asp-controller="DishComposition" asp-action="Edit" asp-route-id="@item.Id" class=" btn btn-sm btn-primary"><i class="bi bi-pencil-square"></i>Edit</a>&nbsp;                            
                            @Html.ActionLink("Delete",
                                "Delete", new { id = item.Id },
                                    new { onclick = "return confirm('Do you really want to delete the tag " + @item.Id + "?')" , @class ="btn btn-sm btn-danger"})
                        </div>
                    </td>
                    
                </tr>
            }
        </tbody>
    </table>
</div>

Restaurant/Restaurant/Views/DishComposition/Edit.cshtml
@using System.Collections;
@using Data.Entities;
@using Business.Models;
@using Business.Interfaces;
@using System.Linq;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers


@model DishCompositionEditViewModel


@inject IIngredientService ingredientService
@inject IDishService dishService

@{
    var ingredient = (await ingredientService.GetAllAsync()).ToList().Select(ingr => new
    {
        Name = ingr.Name,
        Id = ingr.Id,
        Measur = ingr.IngredientMeasurement
    }).Where(i => i.Id == Model.IngredientId).FirstOrDefault();

    var dish = (await dishService.GetAllAsync()).ToList().Select(dish => new
    {
        Name = dish.Name,
        Id = dish.Id
    }).Where(i => i.Id == Model.DishId).FirstOrDefault();

}


@if (@Model != null)
{
        <div class="container shadow p-5">
            <div class="form-group d-flex justify-content-center">
                <h2>Edit</h2>
            </div>

            <form method="post">
                <div asp-validation-summary="All"></div>    

                <input type="hidden" asp-for="Id" />
                <input type="hidden" asp-for="DishId" />
                <input type="hidden" asp-for="IngredientId" />

                <table class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th scope="col">Id</th>
                            <th scope="col">DishId</th>
                            <th scope="col">IngredientId</th>
                            <th scope="col">Current Amount</th>
                            <th scope="col">Measurement</th>
                            <th scope="col">New Amount</th>
                            <th scope="col">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td width="3%">
                                @Model.Id
                            </td>
                            <td width="17%">
                                @dish.Name
                            </td>
                            <td width="20%">
                                @ingredient.Name
                            </td>
                            <td width="5%">
                                @Model.Amount
                            </td>
                            <td width="20%">
                                @ingredient.Measur
                            </td>
                            <td width="15%">
                                <div class="form-group">
                                    <input type="number" class="form-control mb-3" asp-for="Amount" placeholder="Enter Amount">
                                    <span asp-validation-for="Amount" class=" alert-danger"></span>
                                </div>
                            </td>

                            <td width="5%">
                                @Html.ActionLink("Delete",
                            "Delete", new { id = @Model.Id },
                            new { onclick = "return confirm('Do you really want to delete the tag " + @Model.Id + "?')" , @class ="btn btn-sm btn-danger"})
                            </td>

                            <tr>
                    </tbody>
                </table>

                <div class="form-group d-flex justify-content-center">
                    <button type="submit" class="btn btn-lg btn-primary p-2"><i class="bi bi-file-plus-fill"></i>Save</button>
                    <div>&nbsp;</div>
                    <div>&nbsp;</div>
                    <div>&nbsp;</div>
                    <a asp-controller="DishComposition" asp-action="Details" class="btn btn-lg btn-warning p-2">Back To List</a>
                    <div>&nbsp;</div>
                    <div>&nbsp;</div>
                    <div>&nbsp;</div>
                    <a asp-controller="Dish" asp-action="Details" class="btn btn-lg btn-info p-2">Back To Dish</a>
                </div>
            </form>
        </div>
}

else{
    <div>
        <h4 class="text-center">Oops, dish composition was not found :'(</h4>
    </div>
}

<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.5.1.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/jquery.validate.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.10/jquery.validate.unobtrusive.min.js"></script>