Restaurant/Restaurant/Controllers/CartController.cs
using Business.Interfaces;
using Data.Entities;
using Data.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Restaurant.Models;
using Business.Models;
using Newtonsoft.Json;

namespace Restaurant.Controllers
{
    public class CartController : Controller
    {
        private readonly IDishService _dishService;
        private Cart cart;

        public CartController(IDishService dishService, Cart cartService)
        {
            _dishService = dishService;
            cart = cartService;
        }

        public RedirectToActionResult AddToCart(int Id, string returnUrl)
        {
            DishModel dish = _dishService.GetAllAsync().Result.FirstOrDefault(d => d.Id == Id);

            if (dish is not null)
                cart.AddItem(dish, 1);
            return RedirectToAction("Index", new {returnUrl});
        }
        public RedirectToActionResult RemoveFromCart(int dishId, string returnUrl)
        {
            DishModel dish = _dishService.GetAllAsync().Result.FirstOrDefault(d => d.Id == dishId);
            if(dish is not null)
                cart.RemoveLine(dish);
            return RedirectToAction("Index", new { returnUrl });
        }
        public ViewResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }
    }
}

Restaurant/Restaurant/Controllers/IngredientController.cs
using Business.Interfaces;
using Business.Models;
using Data.Data;
using Data.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Restaurant.Models;
using static Restaurant.Constants;

namespace Restaurant.Controllers
{
    public class IngredientController : Controller
    {
        private readonly IIngredientService _ingredientService;
        public IngredientController(IIngredientService ingredientService)
        {
            _ingredientService = ingredientService;
        }

        [Authorize(Roles = $"{Constants.Roles.Administrator},{Constants.Roles.Manager}")]
        public async Task<IActionResult> Index(string searchString)
        {
            var ingredients = await _ingredientService.GetAllAsync();
            if (!String.IsNullOrEmpty(searchString))
            {
                ingredients = ingredients.Where(s => s.Name!.Contains(searchString));
            }
            return View(ingredients.ToList());
        }


        [HttpPost]
        [Authorize(Roles = $"{Constants.Roles.Administrator},{Constants.Roles.Manager}")]
        public async Task<IActionResult> CreateAsync(Ingredient ingredient)
        {
            if(ingredient.ImportDate>ingredient.ExpirationDate)
            {
                ModelState.AddModelError("ImportDate", "Import date cannot be later than Expiration date");
            }
            if (ModelState.IsValid)
            {
            await _ingredientService.AddAsync(ingredient);
            return RedirectToAction("Index");
            }
            return View(ingredient);
        }

        [Authorize(Roles = $"{Constants.Roles.Administrator},{Constants.Roles.Manager}")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpGet]
        [Authorize(Roles = $"{Constants.Roles.Administrator},{Constants.Roles.Manager}")]
        public async Task<ActionResult> EditAsync(int id)
        {
            var ingred = await _ingredientService.GetByIdAsync(id);

            return View(ingred);
        }

        [HttpPost]
        [Authorize(Roles = $"{Constants.Roles.Administrator},{Constants.Roles.Manager}")]
        public async Task<ActionResult> EditAsync(Ingredient ingredient)
        {
            if (ingredient.ImportDate > ingredient.ExpirationDate)
            {
                ModelState.AddModelError("ImportDate", "Import date cannot be later than Expiration date");
            }
            if (ModelState.IsValid)
            {
            await _ingredientService.UpdateAsync(ingredient);
            return RedirectToAction("Index");
            }
            return View(ingredient);
        }

        [Authorize(Roles = $"{Constants.Roles.Administrator},{Constants.Roles.Manager}")]
        public async Task<IActionResult> DeleteAsync(int id)
        {
            await _ingredientService.DeleteAsync(id);
            ViewBag.Messsage = "Record Delete Successfully";
            return RedirectToAction("Index");
        }

    }
}

Restaurant/Restaurant/Controllers/UserController.cs
using Business.Interfaces;
using Business.Services;
using Data.Entities;
using Data.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Restaurant.Models;

namespace Restaurant.ControllersControllers
{
    public class UserController : Controller
    {
        private readonly IIndentityService _identityservice;
        private readonly SignInManager<ApplicationUser> _signInManager;

        public UserController(IIndentityService identityservice, SignInManager<ApplicationUser> signInManager)
        {
            _identityservice = identityservice;
            _signInManager = signInManager;
        }

        [Authorize(Policy = "RequireAdmin")]
        public IActionResult Index()
        {
            var users = _identityservice.GetAll();
            return View(users);
        }
        [Authorize(Policy = "RequireAdmin")]
        public IActionResult ChangeInfo()
        {
            return View();
        }
        [Authorize(Policy = "RequireAdmin")]
        public async Task<IActionResult> Edit(string id)
        {
            var user = _identityservice.GetById(id);
            var roles = _identityservice.GetRoles();

            var userRoles = await _signInManager.UserManager.GetRolesAsync(user);

            var roleItems = roles.Select(role =>
                new SelectListItem(
                    role.Name,
                    role.Id,
                    userRoles.Any(ur => ur.Contains(role.Name)))).ToList();

            var vm = new EditUserViewModel
            {
                User = user,
                Roles = roleItems
            };

            return View(vm);
        }

        [HttpPost]
        [Authorize(Policy = "RequireAdmin")]
        public async Task<IActionResult> OnPostAsync(EditUserViewModel data)
        {
            var user = _identityservice.GetById(data.User.Id);
            if (user == null)
            {
                return NotFound();
            }

            var userRolesInDb = await _signInManager.UserManager.GetRolesAsync(user);

            //Loop through the roles in ViewModel
            //Check if the Role is Assigned In DB
            //If Assigned -> Do Nothing
            //If Not Assigned -> Add Role

            var rolesToAdd = new List<string>();
            var rolesToDelete = new List<string>();

            foreach (var role in data.Roles)
            {
                var assignedInDb = userRolesInDb.FirstOrDefault(ur => ur == role.Text);
                if (role.Selected)
                {
                    if (assignedInDb == null)
                    {
                        rolesToAdd.Add(role.Text);
                    }
                }
                else
                {
                    if (assignedInDb != null)
                    {
                        rolesToDelete.Add(role.Text);
                    }
                }
            }

            if (rolesToAdd.Any())
            {
                await _signInManager.UserManager.AddToRolesAsync(user, rolesToAdd);
            }

            if (rolesToDelete.Any())
            {
                await _signInManager.UserManager.RemoveFromRolesAsync(user, rolesToDelete);
            }

            user.FirstName = data.User.FirstName;
            user.LastName = data.User.LastName;
            user.Email = data.User.Email;

            _identityservice.Update(user);

            return RedirectToAction("Edit", new { id = user.Id });
        }
    }
}

Restaurant/Restaurant/Views/Shared/DishSummary.cshtml
@using Business.Models
@using Business.Infrastructure
@model DishModel
@using Microsoft.AspNetCore.Identity
@using Data.Entities

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


<div class="col col-sm-3">
                            
        <div class="card card-body">



            @if (User.IsInRole("Administrator"))
            {
            <a asp-controller="Dish" asp-action="Edit" asp-route-id="@Model.Id" class="a_dish_menu">
                <div class="text-center">
                    <img src="@Model.ImgPath.ToString()" class="img-fluid mb-3" alt="@Model.Name">
                </div>
                <span class="float-right font-weight-bold">@Model.Price ₴</span>
                <h6 class="text-truncate">@Model.Name</h6>
                <p class="small">@Model.Description</p>
            </a>   
            }
            else
            {
                <div class="text-center">
                    <img src="@Model.ImgPath.ToString()" class="img-fluid mb-3" alt="@Model.Name">
                </div>
            <span class="float-right font-weight-bold">@Model.Price ₴</span>
                <h6 class="text-truncate">@Model.Name</h6>
                <p class="small">@Model.Description</p>
            }

           <form id="@Model.Id" asp-action="AddToCart" asp-controller="Cart" method="post">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()"/>
        <div class="text-center">
            <button type="submit" class="btn btn-outline-warning">Choose</button>
        </div>
        </form>
        </div>
</div>

Restaurant/Restaurant/Views/Shared/ErrorPage.cshtml
@model ErrorViewModel
@{
    ViewData["Title"] = "ErrorPage";
    
}

<div><h2 class="text-danger">An error occurred while processing your request.</h2></div>

<div>
    <img src = "https://www.kibrispdr.org/data/993/500-error-page-html-template-45.gif"   style="max-width:100%"  />
</div>

<div>RequestedUrl :@Model.RequestedUrl is @Model.ExceptionMessage = @ViewData["statusCode"]</div>

Restaurant/Restaurant/Views/Shared/ReservateTable.cshtml
@using System.Collections;
@using Data.Entities;
@using Business.Models;


@model RestaurantTable

<div class="col-lg-4" id="container">
                     <h3> @Model.Id</h3>
                    <h3> @Model.Name</h3>
                    <h3>@Model.Zone</h3>
                    <p>
<a class="btn btn-warning" asp-controller="RestCart" asp-action="addToCard" asp-route-id="@Model.Id">Добавить в корзину</a></p>
                </div>

Restaurant/Restaurant/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Data.Entities

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="./css/scroll.css">      
    <link rel="shortcut icon" href="~/img/favicon.png" type="image/png">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;1,300&display=swap" rel="stylesheet">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="@Url.Action("Index", "Home")">SuperPuperRest</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-item nav-link" href="@Url.Action("Index", "Home")">Main</a>
                    <a class="nav-item nav-link" href="@Url.Action("Index", "Dish")">Menu</a>            
                    <a class="nav-item nav-link" href="@Url.Action("Index", "RestaurantTable")">Reservation</a>   

                    @if (User.IsInRole("Administrator"))
                        {
                        <a class="nav-item nav-link" href="@Url.Action("Details", "Dish")">Dish Details</a>
                        <a class="nav-item nav-link" href="@Url.Action("Details", "DishComposition")">Dish Composition</a>
                        <a class="nav-item nav-link" href="@Url.Action("", "User")">Users</a>
                        }

                    @if (User.IsInRole("Administrator") || (User.IsInRole("Manager")))
                        {
                            <a class="nav-item nav-link" href="@Url.Action("Index", "Ingredient")">Ingredients</a>
                        }
                </div>
            </div>
            <partial name="_LoginPartial" />
            <a class="nav-item nav-link" href="@Url.Action("Index", "Cart")"><img src="~/img/basket.png" alt="Basket"/></a>
        </nav>        
    </header>
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Restaurant - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/scroll.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>